name: Echo Variable

on:
  push:
    branches:
      - main  

jobs:
  echo-variable:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo Variable Name and Value
        run: |
          echo "Variable Name: MY_VARIABLE"
          echo "Variable Value: ${{ vars.MY_VARIABLE }}"
